name: Create and Push Agent TGZ to Main

on:
  push:
    branches:
      - main
    paths:
      - 'apps/agent/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.5.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build and bundle
        run: |
          cd apps/agent
          yarn bundle

      - name: Rename bundle
        run: mv apps/agent/dist/*.tgz apps/agent/dist/agent-${{ github.sha }}.tgz

      - name: Upload TGZ as artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifact_name="agent-${{ github.sha }}.tgz"
          artifact_path="apps/agent/dist/$artifact_name"
          
          # Create a new artifact
          response=$(curl -sS -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
            -d "{\"name\":\"$artifact_name\",\"retention_days\":1}")
          
          upload_url=$(echo $response | jq -r .upload_url)
          
          # Upload the artifact
          curl -sS -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/gzip" \
            -T "$artifact_path" \
            "$upload_url"
          
          echo "Artifact $artifact_name uploaded successfully"
